version: "3.8"

services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: xxxz
      MYSQL_DATABASE: cloud
    networks:
      - cloudappnetwork
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xxxz
      MYSQL_DATABASE: cloud
      MYSQL_PASSWORD: xxxz
    expose:
      - 3306
    ports:
      - "3309:3306"
    networks:
      - cloudappnetwork

    
    volumes:

      - mysql_data:/var/lib/mysql
      - ./studentinformation_backup.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  cloudappnetwork:


volumes:
  mysql_data:
